README.md

adding culture blog

---

README.md

Adding a PR for a new blog post under the educational section that outlines a basic checklist for areas to focus on when joining a new SRE org within a company.

adding check list

---

README.md

Hi @dastergon, this PR do the following:
- add twitter account for the SREBook
Thank you again!

add new twitter: SREBook

---

README.md

Hi @dastergon , this pr include the following:
- add a new entry in blogs section for highscalability.com
- sort blog entries by alpha order
I have few suggestions to come. I will create one PR per new entry.
Thank you for your awesome-sre!

add highscalability.com blog and sort blog entries

---

README.md

Hi @dastergon, this PR add the following:
- add twitter account highscal
Thank you!

add new twitter: highscal

---

README.md

Update Jesse Twitter to real full name and new gig

---

README.md

* Add the PagerDuty Incident Response URL.  It's a great resource for what folks who are new to on-call.

pagerduty_response

---

README.md

While this is not directly related to SRE, having knowledge of best practices (and more importantly what you *should not* do with a service) is critical for sanity.

Add open AWS guide

---

README.md

Fixed two "techincal"'s

---

README.md

Changed h to H for Jonah Horowitz.

Capitalized "Horowitz"

---

README.md

Corrected the title of the link to "A hierarchy of SRE needs" from "Maslow's hierarchy of SRE needs".

Corrected the title of the link to A hierarchy of SRE needs

---

README.md

sreally never took off. remove it

remove defunct blog

---

README.md

Fast ramp-up is particularly critical for SREs, who often feel like they need to know everything to be successful. This article isn't SRE-specific, but I think it's worth including.

Add: The Ultimate Guide to Structuring a 90-Day Onboarding Plan

---

README.md

Added link to sample chapter of "Systems Performance: Enterprise and the Cloud".
The link is published on the author's page for the book: http://www.brendangregg.com/sysperfbook.html

Added link to sample chapter of "Systems Performance: Enterprise and the Cloud"

---

README.md

An awesome AMA about postmortems.

Add John Allspaw AMA

---

README.md

This is general article about how bugs should be treated in large projects.
TLDR: something failed? Not a problem, let's fix it, and automate things so it won't happen again.

Adds "Building blameless working environment"

---

README.md

Great repository!  I added a link I hope you will like.

Adding SRE Adoption Report article

---

README.md

A duplicated entry was found on the list, so I removed it.

Remove duplicate bacon entry.

---

README.md

Full disclosure: This is from my own blog.

Hiring: Add EM-SRE (a.k.a. SRM) Interview Preparation Tips

---

README.md

The anthonycaiafa.com website doesn't exist anymore so I updated the
link to an archived snapshot from the Wayback Machine.

Fix Incomplete Guide to Cultural Narnia link

---

README.md

I wrote this blog post and was hoping to share it here. Thanks!

Add 'A framework for pragmatic performance engineering'

---

README.md

Added a section for SRE Tools and added a curated list of SRE Tools link.

Added SRE Tools

---

README.md

Added  List of CI tools repo under SRE tools

Added  List of CI tools repo under SRE tools

---

README.md

This is a 24 hour, completely online conference that is free so I thought it would be a great addition to the conference list.

Add ADDO - All Day DevOps Conference

---

README.md

Hi,
A little contribution for everyone visiting or living near Paris, France.
Thanks for all your work!

Add SRE Paris to Meetups

---

README.md

Add new SRE book released by Google - "Building Secure and Reliable Systems"
https://landing.google.com/sre/books/
https://static.googleusercontent.com/media/landing.google.com/en//sre/static/pdf/SRS.pdf

Add new SRE book from Google - Building Secure and Reliable Systems

---

README.md

Hello @dastergon! As we agreed here: https://github.com/dastergon/postmortem-templates/pull/6
I would love to add a new resource to the list if possible:
- [Learn out of mistakes. Postmortems to the rescue.](https://fernandocejas.com/2020/03/21/learn-out-of-mistakes-postmortems/)
One more time, thank you very much for gathering and collecting such amount of useful resources.
Cheers

Add new blog post resource: Postmortems.

---

README.md

Hi,
I am Branko from Manning Publications. I thought our new book might be a good match for this list. What do you think?
Thanks in advance!

added Chaos Engineering: Crash test your applications

---

README.md

Following up to https://github.com/dastergon/awesome-chaos-engineering/pull/93

Add https://chaosengineering.news/ newsletter

---

README.md

https://landing.google.com/sre/resources/practicesandprocesses/training-site-reliability-engineers/

adds Training Site Reliability Engineers report

---

README.md

Link doesn't work, and I couldn't find the article through search

Remove broken link to missing blog post

---

README.md

I have added 2 new Google resources to the list.

Some new Google resources.

---

README.md

Added a link to a blog post on reducing MTTM.

Added a blog post on shrinking MTTM

---

README.md

This is an awesome talk about Life of an SRE at Google in which Van shares about responsibility, day to day tasks.

Add talk on Life of an SRE at Google by JC van Winkel

---

README.md

This talk by Yaniv Aknin contains a lot of SRE culture related things.

Add talk "The SRE I Aspire to Be"

---

README.md

Hey @dastergon 
just removing a dead link for "The Remediation Ballet".
Cheers!

Removing dead link for "The Remediation Ballet"

---

README.md

added linkedin school of sre

---

README.md

Adding a new article in Capacity Planning

Adding a new article in Capacity Planning

---

README.md

#93 reminded me to update my links. 😄

Update links to my articles

---

README.md

The `youtube` Video is not available anymore!

Remove SLA Aware Maintenance for Operators reference 

---

README.md

Hi, me again, I checked with [lychee](https://github.com/lycheeverse/lychee) found more broken links, and removed them.
```
❯ ./lychee ~/workspace/awesome-sre/README.md
⚡ http://distributed-systems-observability-ebook.humio.com/ (error sending request for url (http://distributed-systems-observability-ebook.humio.com/): error trying to connect: dns error: failed to lookup address information: Name or service not known)
⚡ http://some.ops4devs.info/ (error sending request for url (http://some.ops4devs.info/): error trying to connect: dns error: failed to lookup address information: Name or service not known)
🚫 https://www.meetup.com/site-reliability/ [404 Not Found]
🚫 https://rackn.com/sre-white-paper/ [404 Not Found]
```

Remove more broken links

---

.github/workflows/lychee.yml

This Pull Request is going to implement the [Lychee Broken Link Checker](https://github.com/marketplace/actions/lychee-broken-link-checker) action
The action is configured to run on each push and scheduled every seven days.
It will check all links in the README.md and automatically creates issues when it finds broken links.
Please feel free to make any changes to the PR so that it fits your needs.

Add Lychee Link Checker

---

.github/workflows/lychee.yml

I increased the Lychee Link Checker timeout from 60 to 120 seconds this should solve the problem which appeared in #100 && #101

Set timeout for Lychee Link Checker to 120 seconds

---

.github/workflows/lychee.yml

Sorry for all the forth and back should fix #103 fix #105 fix #106

Change max concurrency to 32 should fix #103 #105 #106

---

README.md

Added under Misc articles:
https://www.infoq.com/articles/site-reliability-engineering-mobile-apps/

Updated with new article for Native Mobile Apps

---

README.md

[InfraCloud](infracloud.io) wrote an article on SRE practices for beginners. I hope this is useful for the community.

Adding a misc article:  sre best practices 

---

README.md

Adding the incident.io blog — plenty more posts to come on a weekly basis :)

Add incident.io blog

---

README.md

Removed broken resources and added a new blog, thank you for your time

Removed numerous broken resources from README

---

README.md

Added a blog post into Culture section, fixed 2 links as they have spaces between tags

Added blog, fixed 2 links

---

README.md

I think this link is better as it links to Brendan's blog directly and
includes a bunch of useful commands.

Update link for performance checklist

---

README.md

Adding new book:
Honeycomb’s O’Reilly Book Observability Engineering

Adding Observability engineering book

---

README.md

We have RFC style blog posts (a two part series) detailing the needs of error budget policies. We are explaining a data driven framework and a sample policy document. We thought this could be beneficial for others outside of Expedia Group.

Error Budget Policy - Adoption and practices at Expedia Group

---

README.md

issue-122-Fixing Catchpoint blog link

---

README.md

Adding 2 links for newsletters
- Monitoring Weekly 
- O11y news

Monitoring and Observability Newsletters

---

README.md

Remove dead link to Capability map
